# -*- coding: utf-8 -*-
"""frame_and_text_extracrion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16FU10NYQcWyHY1lDR-lqNHH-l-qRSEa4
"""

!apt-get update
!apt-get install -y tesseract-ocr
!pip install pytesseract
!pip install Pillow
!apt install -y ffmpeg
!pip install -q openai-whisper

import os
import pytesseract
from PIL import Image
import shutil

video_extensions = (".mp4", ".mov", ".mkv", ".avi", ".webm")

video_file = None

for file in os.listdir():
    if file.lower().endswith(video_extensions):
        video_file = file
        break

if video_file:
    print("Video found:", video_file)
else:
    print("No video file found.")

def Task_1(video_file):
  !mkdir -p frames
  !ffmpeg -i "{video_file}" -vf fps=0.2 frames/frame_%04d.jpg

  folder_path = "frames"
  all_text = ""
  valid_ext = (".png", ".jpg", ".jpeg", ".bmp", ".tiff", ".webp")

  for filename in os.listdir(folder_path):
    if filename.lower().endswith(valid_ext):
      image_path = os.path.join(folder_path, filename)

      img = Image.open(image_path)
      text = pytesseract.image_to_string(img)

      all_text += text + "\n"

    folder_name = "frames"

    # # Delete folder
    # if os.path.isdir(folder_name):
    #   shutil.rmtree(folder_name)

    # # Delete video file
    # if os.path.isfile(video_file):
    #   os.remove(video_file)

  return all_text

def Task_2(video_file):
  audio_file = "audio.mp3"

  !ffmpeg -y -i "{video_file}" -vn "{audio_file}"

  !whisper "{audio_file}" --model base.en

  with open("audio.txt", "r") as f:
    all_transcript = f.read()

  # !rm -f *.mp3 *.txt *.srt *.vtt *.json *.tsv

  return all_transcript

from concurrent.futures import ThreadPoolExecutor

with ThreadPoolExecutor() as executor:
  feature1 = executor.submit(Task_1, video_file)
  feature2 = executor.submit(Task_2, video_file)

  output1 = feature1.result()
  output2 = feature2.result()

print(output1)